databases:
  - name: postgres
    ipAllowList: []
    databaseName: server
    user: server

services:
  - type: web
    name: server
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false